In [0]:
import tensorflow as tf
import numpy as np

In [0]:
print(tf.__version__)

2.2.0-rc3


In [0]:
from tensorflow.python.client import device_lib
print(device_lib.list_local_devices())

[name: "/device:CPU:0"
device_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: 11024424749717663109
, name: "/device:XLA_CPU:0"
device_type: "XLA_CPU"
memory_limit: 17179869184
locality {
}
incarnation: 7809540934287367903
physical_device_desc: "device: XLA_CPU device"
]


In [0]:
hello = tf.constant('Hello world!')

In [0]:
print(hello)

tf.Tensor(b'Hello world!', shape=(), dtype=string)


In [0]:
x = tf.constant(5.0, dtype=tf.float32)
y = tf.constant(15.0)

z = x + y

In [0]:
print(z)

tf.Tensor(20.0, shape=(), dtype=float32)


In [0]:
z = tf.add(x,y)

In [0]:
print(z)

tf.Tensor(20.0, shape=(), dtype=float32)


In [0]:
x = tf.constant([[1, 2, 3],[4, 5, 6]]) 
y = tf.constant([[6, 5, 4],[3, 2, 1]]) 
z = tf.add(x,y)
print(z)

tf.Tensor(
[[7 7 7]
 [7 7 7]], shape=(2, 3), dtype=int32)


In [0]:
x = tf.Variable(2, tf.int16)
y = tf.Variable(3, tf.int16)
z = tf.Variable(2, tf.int16)

@tf.function
def example(x, y, z):
  xy = tf.add(x, y)
  return tf.multiply(xy, z)

xyz = example(x, y, z)

In [0]:
print(xyz)

tf.Tensor(10, shape=(), dtype=int32)


In [0]:
x_in = 2*np.ones((3,3))
y_in = 3*np.ones((3,3))
z_in = 2*np.ones((3,3))

xyz = example(x_in, y_in, z_in)

print(xyz)

tf.Tensor(
[[10. 10. 10.]
 [10. 10. 10.]
 [10. 10. 10.]], shape=(3, 3), dtype=float64)


In [0]:
x_in = 2*np.ones((3,2))
y_in = 3*np.ones((3,3))
z_in = 2*np.ones((3,3))

xyz = example(x_in, y_in, z_in)

print(xyz)

ValueError: ignored